services:
  cpu:
    image: registry.gitlab.com/quip.network/quip-protocol/quip-network-node-cpu:latest
    pull_policy: always
    container_name: quip-cpu
    restart: unless-stopped
    profiles:
      - cpu
    env_file:
      - .env
    volumes:
      - ./data:/data
    ports:
      - "20049:20049/udp"
      - "20049:20049/tcp"
      - "80:80/tcp"
      - "443:443/tcp"

  cuda:
    image: registry.gitlab.com/quip.network/quip-protocol/quip-network-node-cuda:latest
    pull_policy: always
    container_name: quip-cuda
    restart: unless-stopped
    profiles:
      - cuda
    env_file:
      - .env
    volumes:
      - ./data:/data
    ports:
      - "20049:20049/udp"
      - "20049:20049/tcp"
      - "80:80/tcp"
      - "443:443/tcp"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]

  qpu:
    image: registry.gitlab.com/quip.network/quip-protocol/quip-network-node-cpu:latest
    pull_policy: always
    container_name: quip-qpu
    restart: unless-stopped
    profiles:
      - qpu
    env_file:
      - .env
    volumes:
      - ./data:/data
    ports:
      - "20049:20049/udp"
      - "20049:20049/tcp"
      - "80:80/tcp"
      - "443:443/tcp"
